export const ADD_INGREDIENT = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_FAILED_INGREDIENTS = "FETCH_FAILED_INGREDIENTS";